### ISSUE TITLE
new role in userauth

### ISSUE THREAD

**Issue by nishant-d** [devtron-labs/roadmap#9] opened 2021-12-03 11:39 UTC
Introduce new roles
1. User role with access to modify cluster and environment also, this user will be above admin and below super admin
2. User role with access to modify configurations only, this user will be able to modify config but not create or delete pipelines

**Comment by anupdhiran** [comment] 2021-12-06 09:35
Duplicate of Devtron#939

**Closed as completed** 2021-12-08 10:25 UTC
